---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.topology.checker.name }}-configmap
  labels:
    helm.sh/chart: {{ include "moira.chart" . }}
    app.kubernetes.io/name: {{ .Values.topology.checker.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  checker.yml: |
    {{- if .Values.datasources.redis}}
    redis:
      {{- toYaml .Values.datasources.redis | nindent 6 }}
    {{- end }}
    {{- if .Values.log }}
    log:
      {{- toYaml .Values.logger | nindent 6 }}
    {{- end }}
    {{- if .Values.microservices.checker }}
    checker:
      {{- toYaml .Values.microservices.checker | nindent 6 }}
    {{- end }}
    {{- if .Values.telemetry }}
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    {{- end }}
    {{- if .Values.datasources.graphite_remote}}
    graphite_remote:
      {{- toYaml .Values.datasources.graphite_remote | nindent 6 }}
    {{- end }}
    {{- if .Values.datasources.prometheus_remote}}
    prometheus_remote:
      {{- toYaml .Values.datasources.prometheus_remote | nindent 6 }}
    {{- end }}
