---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.topology.checker.name }}
  labels:
    helm.sh/chart: {{ include "moira.chart" . }}
    app.kubernetes.io/name: {{ .Values.topology.checker.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.topology.checker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.topology.checker.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/checker-configmap.yaml") . | sha256sum }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
        {{- if not (empty .Values.prometheus.port) }}
        prometheus.io/port: "{{ .Values.prometheus.port }}"
        {{- end }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Values.topology.checker.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Values.topology.checker.name }}-volume
          configMap:
            name: {{ .Values.topology.checker.name }}-configmap
            items:
              - key: checker.yml
                path: checker.yml
      containers:
        - name: {{ .Values.topology.checker.name }}
          image: {{ .Values.topology.checker.image }}
{{- if not (empty .Values.topology.checker.livenessProbe) }}
          livenessProbe:
{{ .Values.topology.checker.livenessProbe | indent 12 }}
{{- end }}
{{- if not (empty .Values.topology.checker.readinessProbe) }}
          readinessProbe: 
{{ .Values.topology.checker.readinessProbe | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/moira
              name: {{ .Values.topology.checker.name }}-volume
          resources:
{{ toYaml .Values.topology.checker.resources | indent 12 }}
