---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.topology.filter.name }}-configmap
  labels:
    helm.sh/chart: {{ include "moira.chart" . }}
    app.kubernetes.io/name: {{ .Values.topology.filter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  filter.yml: |
    {{- if .Values.datasources.redis}}
    redis:
      {{- toYaml .Values.datasources.redis | nindent 6 }}
    {{- end }}
    {{- if .Values.log }}
    log:
      {{- toYaml .Values.logger | nindent 6 }}
    {{- end }}
    {{- if .Values.microservices.filter }}
    filter:
      {{- omit .Values.microservices.filter "retentionConfig" | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.telemetry }}
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    {{- end }}

  storage-schemas.conf: |
{{ .Values.microservices.filter.retentionConfig | indent 4 }}
