---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.topology.notifier.name }}-configmap
  labels:
    helm.sh/chart: {{ include "moira.chart" . }}
    app.kubernetes.io/name: {{ .Values.topology.notifier.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  notifier.yml: |
    {{- if .Values.datasources.redis}}
    redis:
      {{- toYaml .Values.datasources.redis | nindent 6 }}
    {{- end }}
    {{- if .Values.log }}
    log:
      {{- toYaml .Values.logger | nindent 6 }}
    {{- end }}
    {{- if .Values.microservices.notifier }}
    notifier:
      {{- omit .Values.microservices.notifier "senders" "moira_selfstate"| toYaml | nindent 6 }}
      {{- if .Values.microservices.notifier.senders }}
      senders:
      {{- range $key, $value := .Values.microservices.notifier.senders }}
        - sender: {{ $key }}
          {{- range $elem, $elemVal := $value }}
          {{ $elem }}: {{ $elemVal }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.microservices.notifier.moiraSelfState }}
      moira_selfstate:
        {{- omit .Values.microservices.notifier.moiraSelfState "contacts" | toYaml | nindent 6 }}
        {{- if .Values.microservices.notifier.moiraSelfState.contacts }}
        contacts:
        {{- range $key, $value := .Values.microservices.notifier.moiraSelfState.contacts }}
          - contact: {{ $key }}
            {{- range $elem, $elemVal := $value }}
            {{ $elem }}: {{ $elemVal }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.telemetry }}
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    {{- end }}
    {{- if .Values.datasources.graphite_remote}}
    graphite_remote:
      {{- toYaml .Values.datasources.graphite_remote | nindent 6 }}
    {{- end }}
    {{- if .Values.datasources.prometheus_remote}}
    prometheus_remote:
      {{- toYaml .Values.datasources.prometheus_remote | nindent 6 }}
    {{- end }}    
